---
title: "Heatmaps"
output: html_notebook
---


```{r}
#load libraries
library(gplots)
```



```{r}
#read in data
counts = read.csv("../../output/adata_anno.csv")
pheno = read.csv("../../output/obs_anno.csv")
rownames(pheno) = pheno$index
mat = as.matrix(counts[,2:ncol(counts)])
colnames(mat) = names(counts)[2:ncol(counts)]
rownames(mat) = counts$index
```

```{r}
#read marker genes for each cluster
dat_markers= read.csv("../../output/wilcox_markers.csv")
clusters= c("Early","Early_neurons","Late_1.1","Late_1.2","Late_2.1","Late_2.2","Late_2.3","Late_2.4",
                                 "Late_2.5","Late_2.6","Late_neurons","Adult_neurons","Glia_1","Glia_2")

#get top 10 markers for each cluster
markers = character()
for (name in clusters){
  cl = subset(dat_markers,dat_markers$cluster == name)
  print(dim(cl))
  cl = subset(cl, cl$pvals_adj<0.01 & cl$logfoldchanges > 2 & cl$genes != '')
  n_genes = 10
  if (length(cl$genes) > 0){ 
    if (length(cl$genes) < 10){
      n_genes = length(cl$genes)
    }
    markers  = c(markers,as.character(cl$genes[1:(n_genes)]))
  }
}
markers = unique(markers)

#subset matrix for markers
mat_selected = mat[markers,]

#center gene expression values
mat_norm = mat_selected - rowMeans(mat_selected)

#set colours for clusters
colour_palette = c('#ffff00','#1ce6ff','#ff34ff','#ff4a46','#008941','#006fa6', '#a30059','#ffdbe5','#7a4900','#0000a6','#63ffac','#b79762','#004d43','#8fb0ff')

#order data by louvain clusters
pheno$louvain_r1.5 = factor(pheno$louvain_r1.5, levels = clusters)
mat_norm = mat_norm[,order(pheno$louvain_r1.5)]

#create heatmap
extreme = (max(abs(min(mat_norm)),abs(max(mat_norm))))
breaks = seq(from=-extreme, to=max(extreme), length.out=100)


pdf("../../output/heatmap_louvain1.5_labels.pdf", width = 20, height = 18)
color.palette = colorRampPalette(c("blue", "white", "red"))
heatmap.2(mat_norm,Colv = F,Rowv = T, symbreak=TRUE, trace='none', 
          cexRow = 0.5, margins =c(12,9),col=color.palette, breaks = breaks,
          ColSideColors=colour_palette[pheno$louvain_r1.5[order(pheno$louvain_r1.5)]], labCol = F)
dev.off()

#create heatmap without labels
pdf("../../output/heatmap_louvain_1.5.pdf", width = 8, height = 5)
color.palette = colorRampPalette(c("blue", "white", "red"))
heatmap.2(mat_norm,Colv = F,Rowv = T, symbreak=TRUE, trace='none', breaks = breaks,
          cexRow = 1, margins =c(12,9),col=color.palette,
          ColSideColors=colour_palette[pheno$louvain_r1.5[order(pheno$louvain_r1.5)]], labCol = F, labRow = F)
dev.off()



png("../../output/heatmap_louvain1.5_labels.png", width = 20, height = 18, units = "in", res = 300)
color.palette = colorRampPalette(c("blue", "white", "red"))
heatmap.2(mat_norm,Colv = F,Rowv = T, symbreak=TRUE, trace='none', 
          cexRow = 0.5, margins =c(12,9),col=color.palette, breaks = breaks,
          ColSideColors=colour_palette[pheno$louvain_r1.5[order(pheno$louvain_r1.5)]], labCol = F)
dev.off()

#create heatmap without labels
png("../../output/heatmap_louvain_1.5.png", width = 8, height = 5, units = "in", res = 300)
color.palette = colorRampPalette(c("blue", "white", "red"))
heatmap.2(mat_norm,Colv = F,Rowv = T, symbreak=TRUE, trace='none', breaks = breaks,
          cexRow = 1, margins =c(12,9),col=color.palette,
          ColSideColors=colour_palette[pheno$louvain_r1.5[order(pheno$louvain_r1.5)]], labCol = F, labRow = F)
dev.off()


```
