---
title: "Early late comparison"
output:
  html_document:
    df_print: paged
---

```{r}
library(monocle)

tfs = read.table("/home/anna/software/Antler-master/inst/extdata/Annotations/TF_mmusculus_150722.dat",stringsAsFactors = F)
early_sc = "../../output/DE_pseudotime/TF/neural_early_bp_emb_10_smooth_curves_pseudotime.csv"

late_sc = "../../output/DE_pseudotime/TF/neural_bp_85_emb_10__smooth_curves_pseudotime.csv"

genes_early =  read.csv("../../output/DE_pseudotime/TF/neural_early_bp_emb_10_de_pseudotime.csv",stringsAsFactors = F)
genes_late =  read.csv("../../output/DE_pseudotime/TF/neural_bp_85_emb_10__de_pseudotime.csv",stringsAsFactors = F)
```

```{r}
return_curves = function(file){
  sc = read.table(file, sep = ",")
  rownames(sc) = sc$V1
  sc$V1 = NULL
  sc = as.matrix(sc)
  sc =  (sc- rowMin(sc))/(rowMax(sc)-rowMin(sc)) 
  return(sc)
}
```

```{r}
early_curves = return_curves(early_sc)
late_curves = return_curves(late_sc)

genes = c(genes_early$X[genes_early$qval<0.05],genes_late$X[genes_late$qval<0.05])

genes = unique(genes)

genes = genes[genes %in% rownames(early_curves) & genes %in% rownames(late_curves)]

write.csv(genes, "../../output/DE_pseudotime/all_tfs_early_late_bp_onwards_list.csv")

early_curves = early_curves[genes,]
late_curves = late_curves[genes,]

curves = cbind(early_curves,late_curves)

library(gplots)

categories = c(rep(1,100),rep(2,100))

cat_colours = c("magenta","springgreen4")
breaks = seq(0,1,length = 101)
color.palette = colorRampPalette(c("blue", "white", "red"))
png("../../output/DE_pseudotime/all_tfs_early_late_bp_onwards_v2.png", height = 8, width = 6, units = "in", res = 300)
h = heatmap.2(curves, Colv = F, Rowv = T, trace = 'none',ColSideColors=cat_colours[categories], breaks = breaks,col = color.palette,
          cexRow = 0.8,labCol = F,colsep = c(100),sepwidth=c(0.2))
dev.off()


pdf("../../output/DE_pseudotime/all_tfs_early_late_bp_onwards_v2.pdf", height = 8, width = 6)
h = heatmap.2(curves, Colv = F, Rowv = T, trace = 'none',ColSideColors=cat_colours[categories], breaks = breaks,col = color.palette,
          cexRow = 0.8,labCol = F,colsep = c(100),sepwidth=c(0.2))
dev.off()

neurogenic_genes = c("Dlx5","Zfp941","Myt1","Gm5454","Tub","Onecut2","Tshz3","Ebf3","St18","Hes6")

png("../../output/DE_pseudotime/tfs_early_late_neurogenic.png", height = 4, width = 6, units = "in", res = 300)
h = heatmap.2(curves[neurogenic_genes,], Colv = F, Rowv = T, trace = 'none',ColSideColors=cat_colours[categories], breaks = breaks,col = color.palette,
          cexRow = 1.2,labCol = F,colsep = c(37,100,146),sepwidth=c(0.2))
dev.off()
```






