---
title: "Plot all modules heatmap"
output: html_notebook
---

Load libraries
```{r}
library(Antler)
library(gplots)
```


```{r}
#read antler object
m = readRDS("../../output/gene_modules/all_data/antler_obj.RDS")
```




```{r}
#read in data
counts = read.csv("../../output/adata_anno.csv")
pheno = read.csv("../../output/obs_anno.csv")
rownames(pheno) = pheno$index
mat = as.matrix(counts[,2:ncol(counts)])
colnames(mat) = names(counts)[2:ncol(counts)]
rownames(mat) = counts$index
```

```{r}
## load data
adata = readRDS('../../output/slingshot/adata_start_louvain_semisup.rds')
```

```{r}
values_early = adata$slingPseudotime_3[adata$louvain_semisup == "Early_neurons"]
values_late = adata$slingPseudotime_1[adata$louvain_semisup == "Late_neurons"]
values_adult = adata$slingPseudotime_1[adata$louvain_semisup == "Adult_neurons"]
```

```{r}
m$topCorr_DR$genemodules

colors = c()

for (i in 1:length(m$topCorr_DR$genemodules)){
  colors = c(colors,rep(i,length(m$topCorr_DR$genemodules[[i]])))
}

names(colors) = colors

genes = unlist(m$topCorr_DR$genemodules)
names(colors) = genes
colors = as.data.frame(colors)

clusters= c("Early","Early_neurons","Late_1.1","Late_1.2","Late_2.1","Late_2.2","Late_2.3","Late_2.4",
                                "Late_2.5","Late_2.6","Late_neurons","Adult_neurons","Glia_1","Glia_2")

#subset matrix for markers
mat_selected = mat[genes,]

#center gene expression values
mat_norm = t(scale(t(mat_selected)))

mat_norm[mat_norm > 3] = 3
mat_norm[mat_norm < -3] = -3

#set colours for clusters
colour_palette = c('#1f77b4',
 '#ff7f0e',
 '#2ca02c','#2ca02c',
 '#d62728','#d62728','#d62728','#d62728','#d62728','#d62728',
 '#9467bd',
 '#8c564b',
 '#e377c2',
 '#7f7f7f')

#colour_palette_modules = brewer.pal(n = 5, name = "Set3")


#order data by louvain clusters
pheno$louvain_r1.5 = factor(pheno$louvain_r1.5, levels = clusters)
mat_norm = mat_norm[,order(pheno$louvain_r1.5)]

pheno  = pheno[order(pheno$louvain_r1.5),] 


early_neurons = mat_norm[,pheno$louvain_r1.5 == "Early_neurons"]

early_neurons = early_neurons[,order(values_early)]

late_neurons = mat_norm[,pheno$louvain_r1.5 == "Late_neurons"]

late_neurons = late_neurons[,order(values_late)]

adult_neurons = mat_norm[,pheno$louvain_r1.5 == "Adult_neurons"]

adult_neurons = adult_neurons[,order(values_adult)]

eEPs = mat_norm[,pheno$louvain_r1.5 == "Early"]

lEPs = mat_norm[,pheno$louvain_r1.5 %in% c("Late_1.1","Late_1.2","Late_2.1","Late_2.2","Late_2.3","Late_2.4",
                                 "Late_2.5","Late_2.6")]

EGCs = mat_norm[,pheno$louvain_r1.5 %in% c("Glia_1","Glia_2")]

mat_norm = cbind(eEPs,early_neurons,lEPs,late_neurons,adult_neurons,EGCs)

library(pheatmap)

pdf("../../output/gene_modules/all_data/modules_heatmap_v3.pdf")
pheatmap(mat_norm, cluster_rows = F, cluster_cols = F,annotation_row = colors,show_rownames = F, show_colnames = F,annotation_names_row = TRUE)
dev.off()


labels = c()

for (i in 1:length(m$topCorr_DR$genemodules)){
  num = length(m$topCorr_DR$genemodules[[i]])
  half = num/2
  for (j in 1:num){
    if (j == half){
      labels = c(labels,i)
    } else{
      labels = c(labels,"")
    }
  } 
}


library(RColorBrewer)
colour_palette_modules = brewer.pal(n = 10, name = "Set3")
colour_palette_modules = rep(colour_palette_modules, 20)

#create heatmap
#extreme = (max(abs(min(mat_norm)),abs(max(mat_norm))))
extreme = 3
breaks = seq(from=-extreme, to=max(extreme), length.out=100)

png("../../output/gene_modules/all_data/heatmap_all_modules_v3.png", width = 30, height = 40, units = "in", res = 300)
color.palette = colorRampPalette(c("blue", "white", "red"))
heatmap.2(mat_norm,Colv = F,Rowv = F, symbreak=TRUE, trace='none', 
          cexRow = 1.5, margins =c(12,9),col=color.palette,breaks = breaks,
          ColSideColors=colour_palette[pheno$louvain_r1.5], RowSideColors = colour_palette_modules[colors$colors], labCol = F, labRow = F)
dev.off()

labels = c()




```

