---
title: "Plot heatmap with selected neuronal gene modules"
output: html_notebook
---

```{r}
#load libraries
library(gplots)
library(RColorBrewer)
library(slingshot)
```


```{r}
#read in data
counts = read.csv("../../output/adata_anno.csv")
pheno = read.csv("../../output/obs_anno.csv")
rownames(pheno) = pheno$index
mat = as.matrix(counts[,2:ncol(counts)])
colnames(mat) = names(counts)[2:ncol(counts)]
rownames(mat) = counts$index
```

```{r}
## load data
adata = readRDS('../../output/slingshot/adata_start_louvain_semisup.rds')
```
```{r}
values_early = adata$slingPseudotime_3[adata$louvain_semisup == "Early_neurons"]
values_late = adata$slingPseudotime_1[adata$louvain_semisup == "Late_neurons"]
values_adult = adata$slingPseudotime_1[adata$louvain_semisup == "Adult_neurons"]
```


```{r}
#read in gene modules
m = readRDS("../../output/gene_modules/all_data/antler_obj.RDS")

markers = c(m$topCorr_DR$genemodules[[11]],m$topCorr_DR$genemodules[[26]],m$topCorr_DR$genemodules[[23]],m$topCorr_DR$genemodules[[8]],m$topCorr_DR$genemodules[[47]],m$topCorr_DR$genemodules[[55]],m$topCorr_DR$genemodules[[65]],m$topCorr_DR$genemodules[[48]])
colour_code = c(rep(1, length(m$topCorr_DR$genemodules[[11]])) ,rep(2, length(m$topCorr_DR$genemodules[[26]])), rep(3, length(m$topCorr_DR$genemodules[[23]])) , rep(4, length(m$topCorr_DR$genemodules[[8]])) , rep(5, length(m$topCorr_DR$genemodules[[47]])),rep(6, length(m$topCorr_DR$genemodules[[55]])),rep(7, length(m$topCorr_DR$genemodules[[65]])),rep(8, length(m$topCorr_DR$genemodules[[48]])))


clusters= c("Early","Early_neurons","Late_1.1","Late_1.2","Late_2.1","Late_2.2","Late_2.3","Late_2.4","Late_2.5","Late_2.6","Late_neurons","Adult_neurons","Glia_1","Glia_2")

clusters_selected = c("Early_neurons","Late_neurons","Adult_neurons")

#subset matrix for markers
mat_selected = mat[markers,pheno$louvain_r1.5 %in% clusters_selected]
pheno_selected = pheno[pheno$louvain_r1.5 %in% clusters_selected,]

early_neurons = mat_selected[,pheno_selected$louvain_r1.5 == "Early_neurons"]

early_neurons = early_neurons[,order(values_early)]

late_neurons = mat_selected[,pheno_selected$louvain_r1.5 == "Late_neurons"]

late_neurons = late_neurons[,order(values_late)]

adult_neurons = mat_selected[,pheno_selected$louvain_r1.5 == "Adult_neurons"]

adult_neurons = adult_neurons[,order(values_adult)]

mat_selected = cbind(early_neurons, late_neurons, adult_neurons)

#center gene expression values
#mat_norm = mat_selected - rowMeans(mat_selected)
mat_norm = t(scale(t(mat_selected)))

mat_norm[mat_norm > 3] = 3
mat_norm[mat_norm < -3] = -3


#set colours for clusters
colour_palette = c(
 '#ff7f0e',
 '#9467bd',
 '#8c564b')

colour_palette_modules = brewer.pal(n = 8, name = "Set3")


#order data by louvain clusters
pheno_selected$louvain_r1.5 = factor(pheno_selected$louvain_r1.5, levels = clusters_selected)
#mat_norm = mat_norm[,order(pheno_selected$louvain_r1.5)]

#create heatmap
extreme = (max(abs(min(mat_norm)),abs(max(mat_norm))))
breaks = seq(from=-extreme, to=max(extreme), length.out=100)

pdf("../../output/gene_modules/all_data/heatmap_neuronal_modules_labels_v3.pdf", width = 20, height = 50)
color.palette = colorRampPalette(c("blue", "white", "red"))
heatmap.2(mat_norm,Colv = F,Rowv = F, symbreak=TRUE, trace='none', 
          cexRow = 0.5, margins =c(12,9),col=color.palette, breaks = breaks,
          ColSideColors=colour_palette[pheno_selected$louvain_r1.5[order(pheno_selected$louvain_r1.5)]], RowSideColors = colour_palette_modules[colour_code], labCol = F)
dev.off()

#create heatmap without labels
pdf("../../output/gene_modules/all_data/heatmap_neuronal_modules_v3.pdf", width = 4, height = 4)
color.palette = colorRampPalette(c("blue", "white", "red"))
p = heatmap.2(mat_norm,Colv = F,Rowv = F, symbreak=TRUE, trace='none', 
          cexRow = 1, margins =c(12,9),col=color.palette,breaks = breaks,
          ColSideColors=colour_palette[pheno_selected$louvain_r1.5[order(pheno_selected$louvain_r1.5)]], RowSideColors = colour_palette_modules[colour_code], labCol = F, labRow = F)
dev.off()

png("../../output/gene_modules/all_data/heatmap_neuronal_modules_labels_v3.png", width = 20, height = 50, units = "in", res = 300)
color.palette = colorRampPalette(c("blue", "white", "red"))
heatmap.2(mat_norm,Colv = F,Rowv = F, symbreak=TRUE, trace='none', 
          cexRow = 0.5, margins =c(12,9),col=color.palette, breaks = breaks,
          ColSideColors=colour_palette[pheno_selected$louvain_r1.5[order(pheno_selected$louvain_r1.5)]], RowSideColors = colour_palette_modules[colour_code], labCol = F)
dev.off()

#create heatmap without labels
png("../../output/gene_modules/all_data/heatmap_neuronal_modules_v3.png", width = 5, height = 5, units = "in", res = 300)
color.palette = colorRampPalette(c("blue", "white", "red"))
heatmap.2(mat_norm,Colv = F,Rowv = F, symbreak=TRUE, trace='none', cexRow = 1, margins =c(12,9),col=color.palette,breaks = breaks,
          ColSideColors=colour_palette[pheno_selected$louvain_r1.5[order(pheno_selected$louvain_r1.5)]], RowSideColors = colour_palette_modules[colour_code], labCol = F, labRow = F)
dev.off()



#create heatmap without labels
png("../../output/gene_modules/all_data/heatmap_neuronal_modules_cell_labels_v3.png", width = 50, height = 5.5, units = "in", res = 300)
color.palette = colorRampPalette(c("blue", "white", "red"))
heatmap.2(mat_norm,Colv = F,Rowv = F, symbreak=TRUE, trace='none', cexRow = 1,cexCol = 0.4, margins =c(12,9),col=color.palette,breaks = breaks,
          ColSideColors=colour_palette[pheno_selected$louvain_r1.5[order(pheno_selected$louvain_r1.5)]], RowSideColors = colour_palette_modules[colour_code])
dev.off()

```