---
title: "Neuronal gene module functional analysis plots"
output: html_notebook
---


```{r}
modules = c(11,26,23,8,47,55,65,48)
terms = c("GO:0008593","GO:0048667"	,"GO:0007409","GO:0031175","GO:0048812","GO:0099003","GO:0016079","GO:0051588","GO:0099643","GO:0006836","GO:0007269", "GO:0099536","GO:0098662","GO:0007186","GO:0051930","GO:1903530","GO:0044058","GO:0098660"
)

terms = c("GO:0008593","GO:0048667","GO:0007409","GO:0031175","GO:0006836","GO:0007269","GO:0099536","GO:0098660","GO:0007186","GO:0051930","GO:0044058")

#GO:0007389	pattern specification process
#GO:0000904	cell morphogenesis involved in differentiation
# GO:0045664	regulation of neuron differentiation

# GO:0008593	regulation of Notch signaling pathway
#GO:0048667	cell morphogenesis involved in neuron differentiation
# GO:0007409	axonogenesis
# GO:0031175	neuron projection development
# GO:0048812	neuron projection morphogenesis
# GO:0099003	vesicle-mediated transport in synapse
# GO:0016079	synaptic vesicle exocytosis
# GO:0051588	regulation of neurotransmitter transport
# GO:0099643	signal release from synapse
# GO:0006836	neurotransmitter transport
# GO:0007269	neurotransmitter secretion
# GO:0099536	synaptic signaling
# GO:0098662	inorganic cation transmembrane transport
# GO:0007186	G protein-coupled receptor signaling pathway
# GO:0051930	regulation of sensory perception of pain
# GO:1903530	regulation of secretion by cell
# GO:0044058	regulation of digestive system process
# GO:0098660	inorganic ion transmembrane transport


# GO:0008593	regulation of Notch signaling pathway
#GO:0048667	cell morphogenesis involved in neuron differentiation
# GO:0007409	axonogenesis
# GO:0031175	neuron projection development
# GO:0006836	neurotransmitter transport
# GO:0007269	neurotransmitter secretion
# GO:0099536	synaptic signaling
# GO:0098660	inorganic ion transmembrane transport
# GO:0007186	G protein-coupled receptor signaling pathway
# GO:0051930	regulation of sensory perception of pain
# GO:0044058	regulation of digestive system process

# c("regulation of Notch signaling pathway","cell morphogenesis involved in neuron differentiation","axonogenesis","neuron projection development","neurotransmitter transport","neurotransmitter secretion","synaptic signaling","inorganic ion transmembrane transport","G protein-coupled receptor signaling pathway","regulation of sensory perception of pain","regulation of digestive system process")
# 
# "GO:0008593","GO:0048667","GO:0007409","GO:0031175","GO:0006836","GO:0007269","GO:0099536","GO:0098660","GO:0007186","GO:0051930","GO:0044058"
# 
# 
# c("regulation of Notch signaling pathway","regulation of neuron differentiation","axonogenesis","neuron projection development","neuron projection morphogenesis","vesicle-mediated transport in synapse","synaptic vesicle exocytosis","regulation of neurotransmitter transport","signal release from synapse","neurotransmitter transport","neurotransmitter secretion","synaptic signaling","inorganic cation transmembrane transport","G protein-coupled receptor signaling pathway","regulation of sensory perception of pain","regulation of secretion by cell","regulation of digestive system process","inorganic ion transmembrane transport")
```

```{r}
results = data.frame(name = as.character(),p_value = as.numeric(), intersection_size = as.numeric(),module = as.numeric())
for (module in modules){
  dat = read.csv(paste0("../../output/gene_modules/all_data/go_terms/functional_analysis_all/moduleG.M.", module,"_GO_BP.csv"))
  dat = dat[dat$native %in% terms,]
  dat = dat[c("name","p_value","intersection_size")]
  dat$module = module
  results = rbind(results, dat)
}
```


```{r}
library(viridis)
library(ggplot2)
results$module = as.factor(results$module)
results$module = factor(results$module, levels = modules)
results$name = as.factor(results$name)
results$name = factor(results$name, levels = c("regulation of Notch signaling pathway","cell morphogenesis involved in neuron differentiation","axonogenesis","neuron projection development","neurotransmitter transport","neurotransmitter secretion","synaptic signaling","inorganic ion transmembrane transport","G protein-coupled receptor signaling pathway","regulation of sensory perception of pain","regulation of digestive system process"))
results$log_p = -log10(results$p_value)
results$sig = 0
results$sig[results$p_value < 0.01] = 1 
results$sig = as.factor(results$sig)
library(extrafont)
#font_import(paths = "/usr/share/fonts/truetype/myfonts/",prompt = F)
pdf("../../output/go_term_summary_h_neurogenic.pdf", width = 8, height = 3.5)
p=ggplot(results, aes(x=module, y=name)) + geom_point(aes(size = intersection_size,color = results$sig)) +  scale_color_manual(values = c("black","red")) + theme(axis.text = element_text(family = "Helvetica", color = "black",size = 15)) + theme(legend.text = element_text(family = "Helvetica", color = "black",size = 15)) + theme(axis.title=element_text(size=15,family = "Helvetica", color = "black")) + theme_classic()  + theme(text = element_text(family = "Helvetica", color = "black",size = 15)) + theme(axis.text = element_text(family = "Helvetica", color = "black",size = 15)) + ylab("") + xlab("Gene Module") + theme(legend.title = element_blank()) + theme(axis.text.x = element_text(angle = 90))
print(p)
dev.off()



pdf("../../output/go_term_summary_v_neurogenic.pdf", width = 3, height = 6.5)
p=ggplot(results, aes(x=name, y=module)) + geom_point(aes(size = intersection_size,color = results$sig)) +  scale_color_manual(values = c("black","red")) + theme(axis.text = element_text(family = "Helvetica", color = "black",size = 15)) + theme(legend.text = element_text(family = "Helvetica", color = "black",size = 15)) + theme(axis.title=element_text(size=15,family = "Helvetica", color = "black")) + theme_classic()  + theme(text = element_text(family = "Helvetica", color = "black",size = 15)) + theme(axis.text = element_text(family = "Helvetica", color = "black",size = 15)) + ylab("") + ylab("Gene Module") + theme(legend.title = element_blank()) + theme(axis.text.x = element_text(angle = 90))
print(p)
dev.off()
```

```{r}
results$log_padj = -log10(results$p_value)
names(results)[2] = "padj"
write.csv(results, "../../source_data/Fig3b.csv", row.names = F)
getwd()
```


